id: I4A1C3186
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-13T03:09:38+00:00'
last_modified: '2022-06-10T04:37:29.967492+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8823
  title: དགོངས་གཏེར་བཀའ་ཐང་དང་དེའི་འགྲེལ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C95B:
      image_group_id: I1KG8873
      title: Volume 1 of dgongs gter bka' thang dang de'i 'grel pa
      total_pages: 114
      order: 1
      base_file: C95B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
